### PR TITLE
Upgrading NAN to 2.x and supporting Node v4.0.0

### PR DESCRIPTION
**Pull request by edsadr**

### CODE REVIEW

**Comment by moll** [comment]
Hey, thanks, mate! Other than the version bump (let's do that only when the cutting a release) and a redundant `return`, superb!

**Comment by edsadr** [comment]
I am removing the version bump, but don't understand about the redundant return?

**Comment by moll** [comment]
Haa, I did the same thing to Travis: https://github.com/moll/node-syslogh/blob/4565048ecda22ef85f8b7de35132528bc4baa759/.travis.yml

I did see building Syslogh.js for Node v0.10 is failing these days, so that's why I haven't yet gotten around to merging this. You wouldn't happen to know off the top of your head why node-gyp fails on v0.10? This fails on master too, so nothing _you_ broke. :)
```
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
```

Thanks for undoing the bump! The redundant returns are `return` statements at the end of what I believe now to be `void` functions.

**Comment by moll** [comment]
Hmm, seems the Zlib error when node-gyp did its thing on Node v0.10 was intermittent and no longer fails. Yay.

**Comment by edsadr** [comment]
those return are replacing `NanReturnUndefined();` those are required by NAN .. so... I am undoing the travis change so you can merge

**Comment by moll** [comment]
No need to undo but thanks. Already ahead of you. :)
I merged it to a temporary branch named `node-v4`.

**Comment by moll** [comment]
As for returns, wouldn't those be equivalent to leaving them out given that they don't really return anything. Aren't those functions `void`?

**Comment by edsadr** [comment]
Awesome... then I will wait for the new version :) in npm

**Comment by moll** [comment]
I don't really have Node v4 installed as it's not in Homebrew yet and I can't be bothered to install it manually, so I'm depending on Travis and you to know if it works. :D

**Comment by moll** [comment]
Hey, Node v4 seems not to build. Does it work on your system?
The error log is here: https://travis-ci.org/moll/node-syslogh/jobs/79686044

**Comment by moll** [comment]
If you have any fixes for that, base them on the node-v4 branch if you don't mind. :innocent:

**Comment by edsadr** [comment]
It is working for me, check my screenshot:

https://cloudup.com/cobMiinFgX6

**Comment by moll** [comment]
That's weird then. I see the build where you included v4 in Travis also failed, so it couldn't have been me removing those 3 `return` statements...

**Comment by edsadr** [comment]
did you update NAN in dependencies?  `"nan": "^2.0.9"`

**Comment by edsadr** [comment]
sorry.. I know what is going on... travis need more stuff to work with V4, please check this travis file: https://github.com/node-xmpp/node-expat/blob/master/.travis.yml

**Comment by moll** [comment]
Great. Thanks for the hint! All passing now. Will cut a release in a sec.

**Comment by moll** [comment]
v1.2.0 is out to play with. Thanks again!

**Pull request merged**
